# .pre-commit-config.yaml
repos:
  - repo: https://github.com/awslabs/git-secrets
    rev: v1.4.0
    hooks:
      - id: git-secrets
        args: ['--no-verify']  # Force scan even if ignored

  - repo: https://github.com/trufflesecurity/trufflehog
    rev: latest
    hooks:
      - id: trufflehog
        args: ['--fail', '--entropy=False']
        
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline .secrets.baseline']
