project_name: "2025 Portland School Board Election Analysis"
description: "Portland Public Schools Bond Election Analysis"

directories:
  data: "data"
  elections: "data/elections"
  geospatial: "data/geospatial"
  maps: "data/maps"
  census: "data/census"
  html: "html"

input_files:
  votes_csv: "data/elections/2025_election_bond_total_votes.csv"
  precincts_voter_summary_csv: "data/elections/multnomah_precinct_voter_summary.csv"
  precincts_geojson: "data/geospatial/multnomah_elections_precinct_split_2024.geojson"
  voters_file_csv: "data/elections/voters_file.csv"
  acs_households_json: "data/census/acs_B11005_2023_no_minors_multnomah.json"
  census_blocks_geojson: "data/geospatial/tl_2022_41_bg.geojson"
  pps_boundary_geojson: "data/geospatial/pps_district_boundary.geojson"

analysis:
  competitive_threshold: 0.10        # 10% margin = competitive
  tossup_threshold: 0.05             # 5% margin = toss-up
  strong_advantage: 0.20             # 20%+ advantage = strong lean
  lean_advantage: 0.05               # 5%+ advantage = lean

metadata:
  attribution: "Multnomah County Elections Division"
  data_source: "Oregon Secretary of State"
  created_by: "Ken Cavagnolo"
  license: "Public Domain"
