project_name: "2025 Zone 1 Election Analysis"
description: "Portland Public Schools Zone 1 Director Election Analysis"

directories:
  data: "data"
  elections: "data/elections"
  geospatial: "data/geospatial"
  maps: "data/maps"
  tiles: "data/tiles"

input_files:
  votes_csv: "2025_election_zone1_total_votes.csv"
  voters_csv: "multnomah_precinct_voter_totals.csv" 
  boundaries_geojson: "multnomah_elections_precinct_split_2024.geojson"
  voter_locations_csv: "voters_file.csv"
  acs_households_json: "hh_no_minors_multnomah_bgs.json"
  block_groups_shp: "tl_2022_41_bg.shp"
  district_boundaries_geojson: "pps_district_data.geojson"

analysis:
  competitive_threshold: 0.10        # 10% margin = competitive
  tossup_threshold: 0.05             # 5% margin = toss-up
  strong_advantage: 0.20             # 20%+ advantage = strong lean
  lean_advantage: 0.05               # 5%+ advantage = lean

metadata:
  attribution: "Multnomah County Elections Division"
  data_source: "Oregon Secretary of State"
  created_by: "Ken Cavagnolo"
  license: "Public Domain"