# .github/workflows/secret-scanning.yml
name: Secret Scanning
on: [push, pull_request]

jobs:
  scanning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for trufflehog

      - name: TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          args: |
            --fail
            --exclude-paths tests/  # Custom exclusions
            git://github.com/${GITHUB_REPOSITORY} 
            
      - name: GitGuardian Scan
        uses: GitGuardian/gg-shield-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GG_API_KEY: ${{ secrets.GG_API_KEY }}